language: node_js
node_js:
  - "8"
before_deploy: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  local-dir: public
  fqdn: youknow.st
  on:
    branch: dev