language: node_js
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  local-dir: public
  fqdn: youknow.st
  on:
    branch: master